### ISSUE TITLE
[FEATURE] Open Source EmmVRC

### ISSUE THREAD

**Issue by DSquared02** [emmVRC/emmVRC-Public#107]
The closed nature of EmmVRC is not only harmful in the longterm but is also controversial due to the inability to check the code for malware or harmful features embedded. On top of that opensourcing the project would allow developers to pitch in features and create different forks of Emm which would allow users to have options. 

Currently as it stands EmmVRC is hosted on a server, it's online-only which means if the server goes down, you cannot use it. This is bafflingly unnecessary as many mods are able to be run offline completely. If EmmVRC was open source people like you and me could better the mod overall and make it a safer experience for most.

It has been done before, it can be done again. I am convinced the only thing holding Emmy from actually rolling this feature out is the fact they would no longer be the sole developer, worry not. People WILL still donate. Plenty of open source projects THRIVE through things like this.

**Comment by DavisDarvill** [comment]
Furthermore the TOS states any modification of EmmVRC is cause for termination from the server. This is counter-productive. That is all.

**Comment by yui-123** [comment]
open source maybe but the tos stuff is because the first modification people do is remove all its restrictions.

**Comment by DavisDarvill** [comment]
> 
> 
> open source maybe but the tos stuff is because the first modification people do is remove all its restrictions.

Restrictions? It's a mod. There will still be the official fork which will still be what most people use but overall it's still against VRC TOS anyways, can't break a rule's rule with another rule if you aren't gonna bother with the rules lol

**Comment by BLANKE1** [comment]
Mostly what the team is worried about is people just yoinking code for risky functions or making an emmVRC that doesn't have any restrictions on risky functions

**Comment by RinLovesYou** [comment]
You always have to expect people modifying your code for this stuff.
Baritone was originally intended to be google maps for blcok game
then someone's private fork became an AI powered combat bot for 2b2t

Open Sourcing your code will elevate your status as a trusted member of the community and provide you with an onslaught of people who would love to further elevate your project.

I believe EMM could be innovated in any number of ways if the community got to contribute.

**Comment by mmeVRC** [comment]
There are projects to reverse engineer EmmVRC's server side, it's actually not that complex. There are even some right here on GitHub ;) they will most likely be taken down as the developers of EmmVRC don't like to share. For me it's more of a trust / security thing. Do you know what they are storing? do you know how well they are storing it? Is their server safe? We saw what happened with messaging and instead of fixing they just turned it off....

**Comment by DavisDarvill** [comment]
> 
> 
> You always have to expect people modifying your code for this stuff.
> Baritone was originally intended to be google maps for block game
> then someone's private fork became an AI powered combat bot for 2b2t
> 
> Open Sourcing your code will elevate your status as a trusted member of the community and provide you with an onslaught of people who would love to further elevate your project.
> 
> I believe EMM could be innovated in any number of ways if the community got to contribute.

^ this! If Emm was open source I see so much more trust between the users and the creators, Emmy has nothing to lose and everything to gain from doing this. It's something that will probably have some growing pains, but Emm has what most projects don't, a community of people who do indeed care. I wanna see what that community can do to better their own experience.

**Comment by DavisDarvill** [comment]
> 
> 
> There are projects to reverse engineer EmmVRC's server side, it's actually not that complex. There are even some right here on GitHub ;) they will most likely be taken down as the developers of EmmVRC don't like to share. For me it's more of a trust / security thing. Do you know what they are storing? do you know how well they are storing it? Is their server safe? We saw what happened with messaging and instead of fixing they just turned it off....

I wouldn't want an extra team of people that work on an offline version, we should unify everyone. If it's open source than there will no longer be an issue with trust or abuse. Abuse can be targeted and since the community is so strong, anything dangerous can simply be ignored. If we had options, I am sure the official fork of Emm would still be the most popular. And that is not a bad thing.

**Comment by mmeVRC** [comment]
> > There are projects to reverse engineer EmmVRC's server side, it's actually not that complex. There are even some right here on GitHub ;) they will most likely be taken down as the developers of EmmVRC don't like to share. For me it's more of a trust / security thing. Do you know what they are storing? do you know how well they are storing it? Is their server safe? We saw what happened with messaging and instead of fixing they just turned it off....
> 
> I wouldn't want an extra team of people that work on an offline version, we should unify everyone. If it's open source than there will no longer be an issue with trust or abuse. Abuse can be targeted and since the community is so strong, anything dangerous can simply be ignored. If we had options, I am sure the official fork of Emm would still be the most popular. And that is not a bad thing.

I agree, we should unify everyone. Creating small pockets doesn't really solve the problem, imagine a world where it's like "did you get my message?" "No I'm on XXX server" ...... not fun!

I do feel that reverse engineering might help as the dev team can find new ways of patching instead of just disabling functionality. Plus it might prove to them that there is a community itching to help them innovate, fix, and just overall improve EmmVRC.

**Comment by RinLovesYou** [comment]
i just wanna be able to submit fixes myself bro :(

**Comment by DavisDarvill** [comment]
> 
> 
> i just wanna be able to submit fixes myself bro :(

a lot of us do.

**Comment by yui-123** [comment]
i can see the argument for both. like i dont see why not as much as its not like emm realy has anything particularly special. so having it open could be nice

**Comment by DavisDarvill** [comment]
> 
> 
> i can see the argument for both. like i dont see why not as much as its not like emm realy has anything particularly special. so having it open could be nice

Emmy has done something special, she created a community of people as well as a great modification of a game. Those two feats together are worth a lot. If we open source this thing it could be AMAZING.

**Comment by Hordini** [comment]
> There are projects to reverse engineer EmmVRC's server side, it's actually not that complex. There are even some right here on GitHub ;) they will most likely be taken down as the developers of EmmVRC don't like to share. For me it's more of a trust / security thing. Do you know what they are storing? do you know how well they are storing it? Is their server safe? We saw what happened with messaging and instead of fixing they just turned it off....

Our Network has been undergoing a complete rewrite for some time now, which will bring significant improvements with it. So as long as it's not blatantly stolen code, but actual original work, server projects are not of any concerns to us. 

Disabling messaging instead of fixing the issue was a temporary solution. Our Network Manager has been extremely busy this week with work, not having hardly a moment to spare on this project. It was very bad timing for all of this to happen at once. Keep in mind that we are a small team. Emmy works on emmVRC itself, while Brandon work on the Network. That's it for development. I'm just the Community Manager, nothing more.
It's unfortunate that real life and issues get in the way sometimes, but that's just how it is.

**Comment by DavisDarvill** [comment]
> 
> 
> > There are projects to reverse engineer EmmVRC's server side, it's actually not that complex. There are even some right here on GitHub ;) they will most likely be taken down as the developers of EmmVRC don't like to share. For me it's more of a trust / security thing. Do you know what they are storing? do you know how well they are storing it? Is their server safe? We saw what happened with messaging and instead of fixing they just turned it off....
> 
> Our Network has been undergoing a complete rewrite for some time now, which will bring significant improvements with it. So as long as it's not blatantly stolen code, but actual original work, server projects are not of any concerns to us.
> 
> Disabling messaging instead of fixing the issue was a temporary solution. Our Network Manager has been extremely busy this week with work, not having hardly a moment to spare on this project. It was very bad timing for all of this to happen at once. Keep in mind that we are a small team. Emmy works on emmVRC itself, while Brandon work on the Network. That's it for development. I'm just the Community Manager, nothing more.
> It's unfortunate that real life and issues get in the way sometimes, but that's just how it is.

Well, open sourcing your project would indeed help with development, not only could there be a group of people who work on an offline version that does not require some server to operate on, but we could also have plenty of people helping Emmy and ensuring the quality and quantity of updates become more frequent! Proprietary software isn't good and I have several friends that refuse to use your mod due to the fact it's closed-source.

I do hope the decision is made to make the source-code public and allow anyone to assist with development.

**Comment by Hordini** [comment]
Personally, I think having a community driven Repo where everyone participates in developing emmVRC would be great. However, we have to consider it on a broad scale. Providing the source code could lead to troubles. My main concern, as was already mentioned, is the abuse of Risky Functions. Allowing for easy modification of restrictions put in place to specifically limit abuse is difficult to do. emmVRC is currently the most used mod in the community, and the last thing I would want to see is for it to be used as a tool for cheating, harassment, and other malicious activities. This is the exact opposite of what we represent, so that is not an option. There may be some solutions to this, however that is not my decision to make.
Keep in mind, I'm not the developer of emmVRC, so don't take what I say here as anything more than what I personally think. Your points and opinions are valid, and don't go overlooked. Though I ask that you give us some time to consider what we want to do going forward with the future of this project. Though I'm happy to see that some here have expressed an interest in working on emmVRC, which we've worked hard to build up to this point.

Also, as a slight note, the reason that emmVRC is hosted on a server is to make it easier for our users to always be up to date. Trust me when I say this, and this might turn into a slight tangent, keeping a large community up to date on their mods not plausible. Especially for necessary quick fixes. Take a look at the support channels, and see how many people do not keep their mods up to date. emmVRC didn't always depend on a loader. Several months before Il2cpp, it was just straight up emmVRC. However, even right up to the end of Mono, long after we switched to a loader, many people were still using the old broken version. But yeah, that's my two cents on that.

Sorry that got a bit long. Sometimes, once I start typing, I can't stop. ^^'

**Comment by DavisDarvill** [comment]
> 
> 
> Personally, I think having a community driven Repo where everyone participates in developing emmVRC would be great. However, we have to consider it on a broad scale. Providing the source code could lead to troubles. My main concern, as was already mentioned, is the abuse of Risky Functions. Allowing for easy modification of restrictions put in place to specifically limit abuse is difficult to do. emmVRC is currently the most used mod in the community, and the last thing I would want to see is for it to be used as a tool for cheating, harassment, and other malicious activities. This is the exact opposite of what we represent, so that is not an option. I've been thinking of solutions to this, and I'm open to suggestions, however it's not something we can ignore.
> Keep in mind, I'm not the developer of emmVRC, so don't take what I say here as anything more than what I personally think. Your points and opinions are valid, and don't go overlooked. Though I ask that you give us some time to consider what we want to do going forward with the future of this project. Though I'm happy to see that some here have expressed an interest in working on emmVRC, which we've worked hard to build up to this point.
> 
> Also, as a slight note, the reason that emmVRC is hosted on a server is to make it easier for our users to always be up to date. Trust me when I say this, and this might turn into a slight tangent, keeping a large community up to date on their mods not plausible. Especially for necessary quick fixes. Take a look at the support channels, and see how many people do not keep their mods up to date. emmVRC didn't always depend on a loader. Several months before Il2cpp, it was just straight up emmVRC. However, even right up to the end of Mono, long after we switched to a loader, many people were still using the old broken version. Maybe we could do something different with our auto-updates, but I just wanted to explain our reasoning for the current system. But yeah, that's my two cents on that.
> 
> Sorry that got a bit long. Sometimes, once I start typing, I can't stop.
> And one more thing. As for why I locked the thread earlier, I was cleaning up some spam. Over 1200 Issues were submitted in a short amount of time, and I accidentally closed this and a few others. ^^'

thank you for your input, on the topic of Risky Functions I totally understand that as no team wants to be responsible for potential damages that come from your mod, but much like any open source projects I don't see a definitive way to limit what people will do with the software. Thanks for clarifying your intentions when it came to closing and re-opening the topic as that was quite weird at first glance. 

I don't personally have any big gripes with EmmVRC other than the online-only turn it has taken. As you mentioned, previous EmmVRC modules did not require a server and the possibility of blacklisting users as well as the network shutting down is what keeps me hoping that eventually an alternative offline Build of Emm can release. 

For now you guys need time to compose yourselves but I do hope you consider my suggestion, as many others share the sentiment. Keep up the good work and tell Emmy she's doing her best.

**Comment by RinLovesYou** [comment]
Keeping the community up to date with your mod really isn't that hard.

picture this ideal scenario;

Updates are published to github releases. Every update of the mod carries the release date with it.
>simply check the github for newer releases:
>yes: notify user
>no: don't

Regarding risky functions;
Remove them from the open source version :)
Believe me when I say that i barely use them.
They are a fun gimmick to have and you could package them separately as their own closed source mod.
The official repo of EMM will never contain unlocked risky functions unless you want it to.
People may make their own forks but at that point, it would just literally be them creating these from scratch again.

I think that would be a nice solution to the problem.

**Comment by Hordini** [comment]
> Keeping the community up to date with your mod really isn't that hard.
> 
> picture this ideal scenario;
> (it's dirty but viable tbh)
> Updates are published to github releases. Every update of the mod carries the release date with it.
> 
> > simply check the github for newer releases:
> > yes: notify user
> > no: don't
> 
> Regarding risky functions;
> Remove them from the open source version :)
> Believe me when I say that i barely use them.
> They are a fun gimmick to have and you could package them separately as their own closed source mod.
> The official repo of EMM will never contain unlocked risky functions unless you want it to.
> People may make their own forks but at that point, it would just literally be them creating these from scratch again.
> 
> I think that would be a nice solution to the problem.

Yes, that would be a good alternative to updates. Notifications instead of auto-updates. Would be more trustworthy as well, not having to worry about us pushing malicious code to release. Though I can say as much as I want that we would never do that to our community, you never really know. As far as you're concerned, we're just random people on the Internet, and I wouldn't fault you for having those suspicions.
Removing Risky Functions from the Repo was also something I considered. Maybe even make it a separate module that hooks into the "core" emmVRC. Personally, I don't even really use them. They're not creative, and in most cases, aren't needed. It's kind of a "why not?" feature that's fairly simple to add, which has been apart of emmVRC since around it's inception. We wanted to give people access to these features in a non-malicious way, which is yet to be done by anyone else.
But again, these are simply my opinions, and are not meant to be taken as confirmation for any future plans. We'll keep everyone updated on what we plan to do. 😄

**Comment by RinLovesYou** [comment]
Yes I believe the idea of having them as a separate mod would solve any concerns that may be had over giving the community the code for them. 

I really just hope that this conversation has sparked a new interest in making EMM open source.
Many people are passionate about this project and would love to contribute.
I believe EMM could grow into something much grander than it already is :)

**Comment by DavisDarvill** [comment]
> 
> 
> Yes I believe the idea of having them as a separate mod would solve any concerns that may be had over giving the community the code for them.
> 
> I really just hope that this conversation has sparked a new interest in making EMM open source.
> Many people are passionate about this project and would love to contribute.
> I believe EMM could grow into something much grander than it already is :)

Indeed. Development would be so much smoother and all concerns would be settled. There are no real downsides to open-sourcing the game as Emmy could simply add an EULA that allows them to take no responsibility for any harmful modifications made. I'm glad there are more people like me who think this would be an amazing feature.

**Comment by Janni9009** [comment]
Throwing in my 2 cents. Firstly while I'd like emmVRC to be open-source as well, in this community it's sadly a bit infeasible. The instant wenwere to do this, people, specifically monkees as commonly referred to, would immediately bypass any limits that are made to keep other (including non-mod) user's experience unharmed (risky functions) as well as ones made to not give VRC more of a reason to ban mods (Avatar favourites VRC+ requirement). Having a disparity in the sources by removing them would bring up the same "it's a scary black-box" issue again. And to be quite honest, a lot of our users would use a limit-removed version in a heartbeat.
Additionally in terms of code-checking, closed source mods are still reviewed at the VRCMG and auto-updating ones are only allowed to be submitted under special circumstances, and lnly by highly trusted modders.
Also emmVRC can load offline as long as the loader succesfully downloaded it once before, though caching the file may bug out at times.

**Comment by thetrueyoshifan** [comment]
Your wish has been granted.

Take care.
