### ISSUE TITLE
[Feature] Bhaptics support within client

### ISSUE THREAD

**Issue by masterpj555** [emmVRC/emmVRC-Public#1286]
Hey guys.

I was wondering if there is an option to support bhaptics from within the client.

Right now there is a shader a japanese guy wrote for an avatar which "kinda" works but requires a resource heavy screen capture tool that captures colored square splaced over the camera view.
It "works" but it's only fixed strenght and freaks out when you open your vrc-menu. I encourage you guys to look into it and maybe also have a talk to PR of bhaptics if you tell them you made emmvrc the custom client for vrc I'm sure they would send you a tactot suit for development/testing

**Comment by rakosi2** [comment]
I would say this may not fit inside emmVRC as the majority of emmVRC users do not use Bhaptics. This feature would be much better as a standalone mod instead of being incorporated inside emmVRC. Please submit the request in the VRC modding group's discord https://discord.gg/rCqKSvR in the channel, #mod-requests

**Comment by thetrueyoshifan** [comment]
No longer necessary thanks to the existence of Avatar OSC.
