### ISSUE TITLE
Avatar loading error

### ISSUE THREAD

**Issue by BotTheWarrior** [emmVRC/emmVRC-Public#1334]
Whenever I have over 66 avatars in my emmvrc favourite list it glitches out when I switch avatars a few times and doesn't allow me to change into other avatars as it's failing to load. Then after a few minutes I appear as a error avatar. Also, when it glitches out other people's avatar also fail to load.

**Comment by gompocp** [comment]
I'm not on the emm team so don't quote me on this but this is an issue with vanilla vrchat that happens when you cancel a download while unpacking an avatar. If this is the issue I think it is there is a "fix" available for this in the VRCMG discord called "DownloadFix" that adds buttons to get the avatar loading working again. You could try that to see if it fixes this issue for you.

**Comment by BotTheWarrior** [comment]
I'll try it out later, thanks for the fast reply though.

**Comment by thetrueyoshifan** [comment]
This is most likely a VRChat issue, as gompo mentioned. Make sure to let an avatar preview or avatar load fully before switching again, and it shouldn't happen as frequently.
