### ISSUE TITLE
my emmvrc avatars wont load

### ISSUE THREAD

**Issue by Y0K0VR** [emmVRC/emmVRC-Public#1336]
i have a little under 500 avatars (ik i have a problem) but lately its taking longer and longer for them to load in but and they havent loaded yet, currently of writing this it says 0 avatars in the emmvrc list and i dont know if my list has been resat without me knowing it or im just experiencing a bug please help

**Comment by rakosi2** [comment]
500 is the limit because of the VRChat issues, you may want to consider using the mod FavCat if you have that many favorited as it uses its own custom list instead of VRChat's. (VRChat knows about the issue but rather than fixing it they just make VRC+ 4 sets of 25) As for the empty emmVRC list, Do you see a pink or red icon next to the mic icon?

**Comment by Y0K0VR** [comment]
> 500 is the limit because of the VRChat issues, you may want to consider using the mod FavCat if you have that many favorited as it uses its own custom list instead of VRChat's. (VRChat knows about the issue but rather than fixing it they just make VRC+ 4 sets of 25) As for the empty emmVRC list, Do you see a pink or red icon next to the mic icon?

i dont have a pink or red icon next to my mic

**Comment by rakosi2** [comment]
Sorry for not getting back to you. Do you still need help? It would be much easier to provide support over Discord https://discord.gg/emmvrc.

**Comment by thetrueyoshifan** [comment]
Please ask for support in our Discord, linked above.
