### ISSUE TITLE
Change Near Clip distance by client instead of by world

### ISSUE THREAD

**Issue by kevdevrev** [emmVRC/emmVRC-Public#1398]
Hello,
In VRC, the distance two objects can get to your face before disappearing is dependent on the world you are in. I think it would be amazing if you can have it be client-side, independent of worlds so users can adjust it to their needs. 

From the wiki:
http://vrchat.wikidot.com/worlds:guides:render-distance
Near Clip defaults to 0.3. Objects closer than this will be clipped away. Lowering this will allow objects to get closer to the camera. Raising this is not recommended.

**Comment by rakosi2** [comment]
Are you asking about the mod NearClippingPlaneAdjuster to be built into emmVRC? I am not sure if it will be included since there is a standalone mod for it. You can find a list of verified mods in the VRChat Modding Group discord https://discord.gg/7EQCmgrUnH 
https://github.com/Dervali-git/Dervali-VRCMods/tree/master/NearClippingPlaneAdjuster

**Comment by rakosi2** [comment]
I am going to close this ticket because there is a dedicated mod for this linked above.
