### ISSUE TITLE
[BUG] Avatar Favorites list increases CPU load and frametime after it's been closed

### ISSUE THREAD

**Issue by TieDyeTopHat** [emmVRC/emmVRC-Public#1430]
Expected: CPU frametime returning to normal after opening avatar list(without melonloader and emm, this is what it does)
![2021-03-25-PM_03_53_47](https://user-images.githubusercontent.com/59061690/112536306-ab5a8300-8d83-11eb-9a33-e05d60884e47.png)
Actual behavior: CPU load and frametime rise and continue to stay high after the favorites menu has been closed. Disabling the favorites list makes a noticeable change to frametime, but it still remains higher than normal.
![2021-03-25-PM_03_55_16](https://user-images.githubusercontent.com/59061690/112536340-ba413580-8d83-11eb-81db-367b38d0e2a5.png)
![2021-03-25-PM_03_55_55](https://user-images.githubusercontent.com/59061690/112536570-09876600-8d84-11eb-97d9-d5412eb56679.png)
Measured using Desktop+ 2.4 performance graph

Steps to reproduce: Load vrchat, open avatar menu, close avatar menu.

**Comment by KortyBoi** [comment]
I'm not trying to say this is specifically an emmVRC issue, but frame time can vary just from the number of elements being rendered. Like some of the following: individual objects (in a world), amount of UI elements, number of avatars, number of separated meshes on avatars, etc. The list can go on forever.
Basically, the more elements being rendered, the more likely your (or anyone's) frame time will increase. This doesn't necessarily just apply to VRChat, any game takes this into account when being developed.
I think your issue is this: Because emmVRC is copying and pasting an already made VRChat avatar list, a quite a bit extra elements are being rendered (even "off-screen"). There's not much we can do, but we will look into this to try and further optimize the Avatar List in every way we can.

**Comment by thetrueyoshifan** [comment]
Should be improved with emmVRC v2.8.0. If it's still an issue, let me know.
