### ISSUE TITLE
[Feature] New status: Offline

### ISSUE THREAD

**Issue by Jacob1101** [emmVRC/emmVRC-Public#1510]
I do enjoy playing with all of my friends but sometimes you just want to be alone or spend time with a specific friend... without being invited by all the others. That's why I think appearing offline could be a great feature to add. Thank you very much for reading!

**Comment by loukylor** [comment]
It's hard to justify a use for this function when comparing the risks.

Offline mode was a thing in VRChat way back when, but is now inaccessible. Attempting to use it works, but is a big red target to VRChat basically telling them, hey I have a modified client. If you couldn't tell from this, it's very risky to have such a function.

Red exists for a reason. If you don't want to receive invites, simply set your status to red. Some people may assume you're not ok if you set it to red, but simply put something in your status like "I'm fine just don't invites" or do that but on orange then your problem is solved.

**Comment by thetrueyoshifan** [comment]
This is not a safe feature to implement, As Louk explained, it would be a major red flag that mods are in use, and the benefits don't outweigh the downfalls.
