### ISSUE TITLE
 emmvrc cant catch my steam id and no api loaded. 

### ISSUE THREAD

**Issue by ViperGaming44** [emmVRC/emmVRC-Public#1527]
So basically im kinda new to this mod but and ive have like this issue with this mod for like a month now xD, but whenever i press play on vrchat steam and then the green text comes,  but then later it says that it didnt catch my steam id and no api loaded. Does anyone know how to fix this? cus i have reinstalled the mod many times, and also vrchat but still the mod doesnt work for me.

**Comment by thetrueyoshifan** [comment]
emmVRC does not use your Steam ID. Can you send your log?

How to find your Log file:

- go to your game's root folder. It's the folder that contains your Mods folder
- open the MelonLoader folder
- find the file called Latest.log
- drag and drop that file here.

If you see MelonLoader.ModHandler.dll instead of Latest.log, Please update MelonLoader to 0.4.3

**Comment by ViperGaming44** [comment]
so do i just drop it here then? mkay 
[Latest.log](https://github.com/emmVRC/emmVRC-Public/files/6913878/Latest.log)

**Comment by rakosi2** [comment]
There is nothing wrong with that log, What does the green text say?

**Comment by Exandria** [comment]
im experiencing the same issue. here is my log
[MelonLoader_21-08-04_21-42-11.724.log](https://github.com/emmVRC/emmVRC-Public/files/6935369/MelonLoader_21-08-04_21-42-11.724.log)

**Comment by loukylor** [comment]
Those messages are harmless and does not prevent emmVRC from loading. If you need further help please go to our help and support channels at [this Discord](discord.gg/emmvrc)
