### ISSUE TITLE
[Feature] Rotate Avatar Slider & Friends Time Tracker

### ISSUE THREAD

**Issue by ghost** [emmVRC/emmVRC-Public#1604]
**Rotate Avatar Slider** - It would be useful to add a slider which would allow us to turn the small demo avatar in the menu into every direction we want. So it would possible to see it from all the sides at any time.

**Friends Time Tracker** - It would be cool to see how much time you spent with that one specific person inside a lobby together. So it would be easier to tell who is a acquaintance and who is a real friend.

![rotate avatar slider](https://user-images.githubusercontent.com/94863270/142917133-d4778c31-26e4-4629-b07a-d278f61e1d04.png)

![time spent](https://user-images.githubusercontent.com/94863270/142917141-6cc1cc53-8bc0-41a5-8187-5dab24fbff1f.PNG)

.

**Comment by Janni9009** [comment]
For the first request, there's already a standalone mod to do this available in the [VRChat Modding Group](https://discord.gg/7EQCmgrUnH) / through [MelonAssistant](https://github.com/knah/VRCMelonAssistant/releases/latest) called PreviewScroller, so that'd be a wont-add. (unless another dev thinks of a way to improve upon it)
For the second request, I can't really give a rock-solid answer to this as it's not one of my strong-fields, but from my understanding as this isn't an API tracked stat, we'd have to constantly write to a local database or json config for this which isn't exactly optimal as it could potentially corrupt when VRC crashes. It would be better to use external tools like [VRCX](https://github.com/Natsumi-sama/VRCX/releases) for this as it runs independently from VRC, though that adds the drawback of only tracking that stat when both VRChat and VRCX are running.
Oh and obviously neither solution tracks any of your past time, and if your config/DB resets or gets irreperably corrupted, you start all over again.
