### ISSUE TITLE
Radial menu echo option

### ISSUE THREAD

**Issue by Caldoric** [emmVRC/emmVRC-Public#1623]
Long story short up front, the idea here is to have a toggleable option that lets you "mirror" or "echo" whatever is showing up on your hands' radial menus onto your hud, as a sort of "eyes-free" way of navigating said radials. My thought behind this is mostly for RP or similar situations, where constantly looking at your hand(s) to navigate menus, spawn items/effects, etc, can break immersion. Or if you just want to surprise a friend. The result would be to have a smaller, more transparent version of your radials show up in the corner(s) of your visible HUD (possibly with adjustable settings in the main menu somewhere).

**Comment by Janni9009** [comment]
You can already do this completely without mods, ever since the ActionMenu was first introduced in fact. Simply enable "Options > Config > On Hud", change their position with "Options > Config > HUD Position" and set your transparency with "Options > Config > Menu Opacity" for each hand's ActionMenu you wish to change. (they're actually separate, if you usually only use one, then you could pin the other to your HUD permanently for example!)

Additionally if you want it to be a bit more fancy and a lot more technical, with OSC support now, you could write a much more compact and less limiting than the ActionMenus 8 options per page SteamVR Overlay for this purpose; if you've got some (/time to pick up) programming skills in C++ or Unity-flavoured C# (which isn't actually that difficult to pick up, Unity even gives you hands-on tutorials).

**Comment by Caldoric** [comment]
Yeah, I kinda already figured it out in the time since I originally posted this, thanks to a video I stumbled across. Of course, by then, I'd forgotten about this post. I'm surprised it took this long to get a reply tbh.

**Comment by Caldoric** [comment]
As for the coding part... That's definitely interesting, but I think I'll wait for someone else to make a prefab or something. Code doesn't stick in my head too well.
