### ISSUE TITLE
[ BUG ] Avatar search not working.

### ISSUE THREAD

**Issue by NeonGore** [emmVRC/emmVRC-Public#1635]
So, I don't know if this is a common or known issue but I appear to be having issues with using the search avatar feature.
When I press on an avatar I want to use, it appears as a " Error " model instead, but the avatars I already had favorited aren't showing up as error models.

It's like this with almost every avatar that I search up and I may have found the error that is causing this bug?
I'm not sure but I get this error about a few things being missing? Or something similar to that.

I should note that the things I use for VRCHAT are: steam and melon loader, i'm unsure how to fix this bug if it's just a " me " problem.

**Comment by rakosi2** [comment]
This is most definitely because of the VRChat update 1169. Please be patient while we update emmVRC. There is no ETA

**Comment by NeonGore** [comment]
Ah okay, noted!! Wasn't sure if it was because of the update!

**Comment by Xethorak** [comment]
I am having a similar problem, however, when I try to select the Search button in avatars, nothing happens. It is also faded like emm is not installed. I know the feature has not been removed because I have friends who use emm and they can still search avatars. I have uninstalled and re-installed melonloader, the mod, and even vrchat itself. However, nothing seems to fix it.

**Comment by BenjaminZehowlt** [comment]
> 

This is not a bug please join the Discord for assistance and this issue was fixed a while back.
