### ISSUE TITLE
[Feature Request] (<- i think?) Instance history  limitation

### ISSUE THREAD

**Issue by qwearchangel** [emmVRC/emmVRC-Public#1661]
Hello.

This is a problem that have occurred a lot for the last few months on popular events that is invite only.

Due to space being limited to a max of 80 and there are constantly 200+ people wanting to join every week on the most popular nights makes it so there are rules for spots, As in you only get your spot saved for rejoining **_AFTER_** the event have officially started.

Sadly there is a few to a lot of people crashing during the gathering of the event and others will then take their space. Because there are ample time to fix your settings and other stuff before the announced time the gathering is happening. And its first come first serve, you crash you loose **until** the event starts.

Now the problem is about the people not accepting this and is taking the safe spots from others using the EMM instance history during the event. Heck there will be even bigger problem if some of the event hosts and other event workers getting crashed and someone take their space. Luckily the last part haven't really happened yet to some of the events but its just a ticking bomb to happen.

---

### Story is done, now to the real part

The instance history needs to be limited is wont save instances from **Club worlds** that also is **Invite only**. Just to make sure events will be run in a safer and to keep problems away when some idiot take away some important reserved space or from someone that have a safe spot.

And a message to those that have problem with this..... You don't get in or cant stay in during the gathering, then stay out. You are only making a problem for everyone else and especially for the hosts of said event

**Comment by loukylor** [comment]
The issue with this is that there is a real reason to use instance history to get into invite only club worlds. Smaller events without population caps for example. 

I might be wrong here since I don't often deal with large lobbies, but one way to work around is to change the number of people allowed in the world. The number of people that are allowed in a world is actually double the number listed on the world. Just that, if you want to join a world that's over the number listed then you have to have an invite. So, if you want to enforce a certain number of people, just set the world cap to be half of what the max number of people allowed is. If someone tries to join above that cap then VRChat won't allow them to join, even with instance history or an invite.
