### ISSUE TITLE
Emmvrc on quest 2 

### ISSUE THREAD

**Issue by WhiteCodeC** [emmVRC/emmVRC-Public#1668]
I'm wondering how could i open the emmvrc menu on the quest 2, i play vrchat using airlink and steam vr, i can see the logo of emmvrc on quest 2 but i don't know how to open the menu

**Comment by Janni9009** [comment]
Since you're using a PC-linked quest, it behaves like any other PCVR headset, basically it being a quest doesn't matter.
You open the emmVRC menu just like you would normally, even in desktop. Open your QuickMenu and go to the emmVRC tab. If that tab doesn't show up, go to the [emmVRC Discord's](https://discord.gg/emmvrc) support channel and post your latest log.
