### ISSUE TITLE
[question] [future feature (maybe)] Where's the "Portal to friend" feature and what exactly does it do, also is there a force join feature?

### ISSUE THREAD

**Issue by Ender47** [emmVRC/emmVRC-Public#1673]
I may be blind or dumb but like the title says, can someone point me out to where the "portal to friend" option is? I've seen other threads with people talking about it but I can't seem to find it. Also what does that feature do? Does it force join friends or just teleport you to where your friend is in the same world as you.

Also, if this feature doesn't force join your friends in another instance, is there a feature that does that and where is it in the menu? If not then I'd be very useful to have this feature to join friends that're sleeping and forgot to turn off their ask to join in status. (or other reasons)

**Comment by rakosi2** [comment]
"portal to friend" will drop a portal down in front of you so that you and your friend can all go together. It is an old feature and we may remove it soon as it is now part of VRChat with the new 2.0 UI. 

Force join is not possible as every instance has a sort of password and the VRChat API will not tell you that password unless they are green/blue or they allow you to get that password with a join request. Unless you can guess that password (which is 48 hexadecimal long), you can not force join.
