### ISSUE TITLE
pencil new feature that should be added

### ISSUE THREAD

**Issue by jedzox360** [emmVRC/emmVRC-Public#77]
you should add a pencil it be good for communication and drawing and it would be in the menu and you could it change to different colours like the flashlight and you be able to turn it off and on and it would be at the same place where the flashlight is

**Comment by Provini** [comment]
I think this would work local only, as the flashlight is also local only. A pen for others to see will probably have to be on an avatar itself.

**Comment by yui-123** [comment]
the only way that would be possible would be between others with emm it could send something that adds a pen to your finger or something but at that point you already got emm messaging so no real point

**Comment by Janni9009** [comment]
Sadly since a long while back (i think since about a year) you can no longer instantiate networked objects, let alone custom ones (which would only have worked with mod users as well).
As it has been said though, you can easily add a pen to your avatar that everyone can see. There is some ready made prefabs like SnailMarker too.
