### ISSUE TITLE
Steal avatars

### ISSUE THREAD

**Issue by ZeroTwoModz** [emmVRC/emmVRC-Public#83]
You can just steal anyone's avatar even when they have it locked

**Comment by Provini** [comment]
This is a bug in VRChat themselves. In it's bugged state, toggling avatar cloning requires a restart.

**Comment by Janni9009** [comment]
Since you also wrongposted this in risky functions requests, i'll assume you mean this as a feature request.
We will absolutely NOT be adding this as it violates user privacy settings. Even if VRC handles the check for it in a way comparable in incompetence to a dumpster fire it will never be added to emmVRC, or allowed on the VRCMG.
